# SPDX-License-Identifier: MIT
# Copyright (c) 2020 The Authors.

# Authors: Phu Tran          <@phudtran>

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dfts.zeta.com
spec:
  scope: Namespaced
  group: zeta.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: Dft
    plural: dfts
    singular: dft
    shortNames:
      - dft
      - dfts
  validation:
    openAPIV3Schema:
      properties:
        table:
          type: array
          items:
            type: string
        chains:
          type: array
          items:
            type: string
        fwds:
          type: array
          items:
            type: string
  additionalPrinterColumns:
    - name: Status
      type: string
      priority: 0
      JSONPath: .spec.status
      description: The Current Status of the DFT
    - name: Numchains
      type: integer
      priority: 0
      JSONPath: .spec.numchains
      description: The number of chains in the DFT
    - name: CreateTime
      type: string
      priority: 0
      JSONPath: .spec.createtime
      description: Time the object is created
    - name: ProvisionDelay
      type: string
      priority: 0
      JSONPath: .spec.provisiondelay
      description: Time to provision an object from creation
