---
#
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2020 The Authors.
# Authors: Bin Liang  <@liangbin>
#
# Summary: Tasks for Ubuntu specific setup
#
# https://bugs.launchpad.net/cloud-images/+bug/1573095
#remove console=ttyS0 from GRUB_CMD_LINUX_DEFAULT in /etc/default/grub.d/50-cloudimg-settings.cfg, leaving only console=tty1, and then run "sudo update-grub".
#GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0"
# GRUB_CMDLINE_LINUX_DEFAULT="console=tty1"
# $ sudo update-grub
- name: disable serial port 1/2
  become: yes
  command: sed -i 's/ console=ttyS0//g' /etc/default/grub.d/50-cloudimg-settings.cfg

- name: disable serial port 2/2
  become: yes
  command: update-grub

